orsa-scholis/evaweb

.rubocop.yml, config/environments/production.rb, config/initializers/simple_form.rb, config/initializers/simple_form_bootstrap.rb
Exclude BlockLength for initializers and fix LineLengths
=> Make rubocop happy

Gemfile, Gemfile.lock, app/models/answer_possibility.rb, config/environments/test.rb, package.json, spec/models/answer_possibility_spec.rb, spec/rails_helper.rb
=> Test setup

.github/workflows/ruby.yml, app/controllers/surveys_controller.rb, app/models/survey.rb, app/views/surveys/index.html.erb, config/locales/de.yml, config/locales/fr.yml, config/locales/it.yml, spec/factories/surveys.rb, spec/models/survey_spec.rb
=> Add nice root view

app/dashboards/answer_possibility_dashboard.rb, app/dashboards/question_dashboard.rb, app/dashboards/question_group_dashboard.rb, app/views/admin/application/_navigation.html.erb, app/views/layouts/_admin_toolbar.html.erb, app/views/layouts/application.html.erb, app/views/surveys/index.html.erb, app/webpack/stylesheets/admin_toolbar.scss, app/webpack/stylesheets/application.scss, app/webpack/stylesheets/variables.scss, config/locales/de.yml, config/locales/en.yml, config/locales/fr.yml, config/locales/it.yml, db/seed_data/first_survey.rb, db/seed_data/second_survey.rb, db/seeds.rb
Added admin bar and adapted admin tool, translations of models for admin tool
=> Admin Improvements

app/controllers/surveys_controller.rb, app/helpers/survey_link_class_helper.rb, app/models/survey.rb, app/views/surveys/index.html.erb, config/locales/de.yml, config/locales/en.yml, config/locales/fr.yml, config/locales/it.yml, spec/helpers/survey_link_class_helper_helper_spec.rb, spec/models/administrator_spec.rb, spec/models/survey_spec.rb
=> Admin sees all surveys

app/models/answer_possibility.rb, db/migrate/20191220133039_add_more_translations.rb, db/schema.rb, spec/models/answer_possibility_spec.rb
=> Migrations and specs

app/views/devise/confirmations/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/unlocks/new.html.erb, config/environments/development.rb, config/locales/de.yml
There were some helpers called which were relicts of devise-bootstrap gem
Plus fixed development mail sending
=> Fix password reset

Gemfile, Gemfile.lock, app/controllers/admin/surveys_controller.rb, app/helpers/survey_export_helper.rb, app/jobs/admin/survey_export_job.rb, app/models/question.rb, app/views/admin/surveys/_analysis.xlsx.axlsx, app/views/admin/surveys/_raw_data.xlsx.axlsx, app/views/admin/surveys/export.xlsx.axlsx, app/views/admin/surveys/show.html.erb, app/webpack/javascripts/application.js, app/webpack/packs/administrate.js, app/webpack/stylesheets/administrate/application.scss, app/webpack/stylesheets/application.scss, config/initializers/mime_types.rb, config/locales/de.yml, config/locales/en.yml, config/locales/fr.yml, config/locales/it.yml, config/routes.rb, package.json, spec/factories/administrators.rb, spec/jobs/admin/survey_export_job_spec.rb, spec/models/question_spec.rb, spec/rails_helper.rb, spec/requests/admin/surveys_controller_spec.rb, spec/support/complete_survey_spec_helper.rb, yarn.lock
Han mi doch na umentschide es nid mit emene Job z mache wills eigentli an schnell gsi isch und au eifacher und sie tuet ja d Surevys eh erst denn exoprtiere wenn sie dure sind und blockiert so au kei laufendi
closes #11
=> Excel export

README.md
=> Meaningful README

app/views/layouts/application.html.erb, app/views/survey_entries/index.html.erb, app/webpack/stylesheets/application.scss, app/webpack/stylesheets/survey_entries.scss, app/webpack/stylesheets/variables.scss, config/initializers/simple_form_bootstrap.rb, config/locales/de.yml, config/locales/en.yml, config/locales/fr.yml, config/locales/it.yml
=> Improvements

app/controllers/dashboards_controller.rb, app/models/survey.rb, app/views/dashboards/index.html.erb, db/migrate/20200123104233_add_short_url_caching_to_survey.rb, db/schema.rb, spec/models/survey_spec.rb
=> Move short_url to model and cache it

app/models/survey_statistics.rb, app/webpack/javascripts/chart.js, spec/models/survey_statistics_spec.rb
=> Make chart look a bit nicer

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/admin/application_controller.rb, app/controllers/application_controller.rb, app/dashboards/answer_possibility_dashboard.rb, app/helpers/navbar_helper.rb, app/views/layouts/_admin_toolbar.html.erb, app/views/layouts/_navbar.html.erb, app/views/layouts/application.html.erb, app/webpack/stylesheets/admin_toolbar.scss, config/locales/de.yml, config/locales/en.yml, config/locales/fr.yml, config/locales/it.yml, spec/controllers/application_controller_spec.rb, spec/helpers/navbar_helper_spec.rb, spec/requests/survey_entries_controllers_spec.rb, spec/support/survey_entries_controller_spec_helper.rb
Plus other improvements
closes #68
=> Locale switcher

app/views/survey_entries/create.html.erb, app/views/survey_entries/index.html.erb, config/locales/de.yml, config/locales/en.yml, config/locales/fr.yml, config/locales/it.yml
closes #77
* Fixes error message for empty answer possibilities
* Provide more translations other than German
* Remove unused view
=> Provide translations

public/404.html, public/422.html, public/500.html
=> Nice 404 page

app/models/question_group.rb, config/locales/de.yml, config/locales/en.yml, config/locales/fr.yml, config/locales/it.yml, spec/models/question_group_spec.rb
=> Prevent survey relation change on update

.rubocop.yml, Gemfile, app/controllers/admin/surveys_controller.rb, app/controllers/surveys_controller.rb, app/models/submission_tracking.rb, app/views/survey_entries/index.html.erb, config/environments/development.rb, spec/factories/questions.rb, spec/system/survey_happy_path_spec.rb, spec/views/survey_entries/index.html.erb_spec.rb
Added tests & actually use Bullet
=> Test it better

app/views/admin/surveys/_analysis.xlsx.axlsx
Somehow using the description, Excel could not open the document anymore. The only way I found was parameterizing it. Enforcing UTF-8 didn't help either
=> Fix broken Excel format

Gemfile, Gemfile.lock, spec/rails_helper.rb, spec/spec_helper.rb
=> Mock all request to bitly api during specs

app/views/surveys/qrcode.html.erb, app/webpack/stylesheets/admin_toolbar.scss, config/locales/de.yml, config/locales/en.yml, config/locales/fr.yml, config/locales/it.yml, spec/views/surveys/qrcode.html.erb_spec.rb
=> Add print btn to QRCode view
